stages:
  - build
  - deploy

variables:
  NODE_VERSION: "18"
  OUTPUT_DIR: "out"

# Cache node modules for faster builds
cache:
  paths:
    - node_modules/

# Build stage
build:
  stage: build
  image: node:${NODE_VERSION}-alpine
  before_script:
    - apk add --no-cache git
    - npm ci --only=production
  script:
    - npm run build
    - echo "Build completed successfully"
  artifacts:
    paths:
      - out/
    expire_in: 1 hour
  only:
    - main
    - develop
  tags:
    - docker

# Deploy to Azure Static Web Apps Production
deploy-production:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:latest
  before_script:
    - az --version
    - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
  script:
    - echo "Deploying to Azure Static Web Apps Production..."
    - az staticwebapp create --name $AZURE_STATIC_WEB_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --source . --location $AZURE_LOCATION --branch $CI_COMMIT_REF_NAME --app-location "/" --output-location "out" --token $AZURE_STATIC_WEB_APPS_TOKEN --login-with-github-token $GITHUB_TOKEN
    - echo "Production deployment completed successfully"
  environment:
    name: production
    url: https://$AZURE_STATIC_WEB_APP_NAME.azurestaticapps.net
  only:
    - main
  tags:
    - docker
  dependencies:
    - build

# Deploy to Azure Static Web Apps Staging (for develop branch)
deploy-staging:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:latest
  before_script:
    - az --version
    - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
  script:
    - echo "Deploying to Azure Static Web Apps Staging..."
    - az staticwebapp create --name $AZURE_STATIC_WEB_APP_NAME-staging --resource-group $AZURE_RESOURCE_GROUP --source . --location $AZURE_LOCATION --branch $CI_COMMIT_REF_NAME --app-location "/" --output-location "out" --token $AZURE_STATIC_WEB_APPS_TOKEN --login-with-github-token $GITHUB_TOKEN
    - echo "Staging deployment completed successfully"
  environment:
    name: staging
    url: https://$AZURE_STATIC_WEB_APP_NAME-staging.azurestaticapps.net
  only:
    - develop
  tags:
    - docker
  dependencies:
    - build
