stages:
  - build
  - deploy

variables:
  NODE_VERSION: "18"
  OUTPUT_DIR: "out"
  AZURE_STATIC_WEB_APP_NAME: "octobit8"

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:18-alpine
  before_script:
    - apk add --no-cache git
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - out/
    expire_in: 1 hour
  only:
    - main
    - develop

deploy-production:
  stage: deploy
  image: node:18-alpine
  before_script:
    - apk add --no-cache git
    - npm install -g @azure/static-web-apps-cli
  script:
    - swa deploy ./out --deployment-token $AZURE_STATIC_WEB_APPS_API_TOKEN --app-name $AZURE_STATIC_WEB_APP_NAME
  environment:
    name: production
    url: https://$AZURE_STATIC_WEB_APP_NAME.azurestaticapps.net
  only:
    - main
  dependencies:
    - build

deploy-staging:
  stage: deploy
  image: node:18-alpine
  before_script:
    - apk add --no-cache git
    - npm install -g @azure/static-web-apps-cli
  script:
    - swa deploy ./out --deployment-token $AZURE_STATIC_WEB_APPS_API_TOKEN --app-name $AZURE_STATIC_WEB_APP_NAME-staging
  environment:
    name: staging
    url: https://$AZURE_STATIC_WEB_APP_NAME-staging.azurestaticapps.net
  only:
    - develop
  dependencies:
    - build
