import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuItems = [
    { href: "/about", label: "About" },
    {
      label: "Services",
      dropdown: [
        { href: "/services/website-development", label: "Website Development" },
        { href: "/services/it-staffing", label: "IT Staffing" },
        { href: "/services/mobile-app-development", label: "Mobile App Development" },
        { href: "/services/custom-software-development", label: "Custom Software Development" },
      ],
    },

    {
      label: "Industries",
      dropdown: [
        { href: "/industries/healthcare", label: "Healthcare" },
        { href: "/industries/edtech", label: "EdTech" },
        { href: "/industries/travel", label: "Travel" },
        { href: "/industries/hospitality", label: "Hospitality" },
        { href: "/industries/logistics", label: "Logistics" },
        { href: "/industries/retail", label: "Retail" },
        { href: "/industries/real-estate", label: "Real Estate" },
        { href: "/industries/banking-finance", label: "Banking & Finance" },
      ],
    },
    {
      label: "Solutions",
      dropdown: [
        { href: "/services/devops", label: "DevOps & Cloud" },
        { href: "/services/data-analytics", label: "Data Analytics" },
        { href: "/services/ai-development", label: "AI Agent Development" },
      ],
    },


    { href: "/careers", label: "Careers" },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen flex flex-col`}
      >
        {/* Header with Navigation */}
        <header className="bg-gray-900 shadow sticky top-0 z-50">
          <nav className="container mx-auto flex items-center justify-between py-3 px-4 border-b border-gray-800 min-h-[72px]">
            {/* Logo and Title */}
            <Link href="/" className="flex items-center gap-3 group">
              <Image src="/logo.png" alt="octobit8 logo" width={160} height={80} />
            </Link>
            {/* Desktop Menu - centralized */}
            <ul className="hidden md:flex gap-6 text-gray-100 font-medium flex-1 justify-center items-center">
              {menuItems.map((item) => {
                const isActive = typeof window !== 'undefined' && window.location.pathname === (item.href || (item.dropdown && item.dropdown[0]?.href));
                if (item.dropdown) {
                  return (
                    <li key={item.label} className="relative group">
                      <button
                        className={`px-4 py-2 transition focus:outline-none flex items-center gap-1 ${isActive ? 'text-blue-400' : ''}`}
                        type="button"
                      >
                        {item.label}
                        <svg className="w-4 h-4 ml-1" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" /></svg>
                      </button>
                      <ul className="absolute left-0 mt-3 w-48 bg-gray-900 text-white rounded shadow-lg opacity-0 group-hover:opacity-100 group-hover:visible invisible transition-opacity z-50 border border-gray-700">
                        {item.dropdown.map((sub) => {
                          const isSubActive = typeof window !== 'undefined' && window.location.pathname === sub.href;
                          return (
                            <li key={sub.href}>
                              <Link
                                href={sub.href}
                                className={`block px-4 py-2 rounded transition ${isSubActive ? 'text-blue-400' : ''}`}
                              >{sub.label}</Link>
                            </li>
                          );
                        })}
                      </ul>
                    </li>
                  );
                } else if (item.href) {
                  return (
                    <li key={item.href}>
                      <Link
                        href={item.href}
                        className={`px-4 py-2 transition focus:outline-none ${isActive ? 'text-blue-400' : ''}`}
                      >
                        {item.label}
                      </Link>
                    </li>
                  );
                }
                return null;
              })}
            </ul>
            {/* Mobile Hamburger */}
            <div className="md:hidden flex items-center ml-auto">
              <input id="menu-toggle" type="checkbox" className="hidden peer" />
              <label htmlFor="menu-toggle" className="cursor-pointer flex flex-col gap-1.5 p-2">
                <span className="block w-6 h-0.5 bg-gray-100 rounded"></span>
                <span className="block w-6 h-0.5 bg-gray-100 rounded"></span>
                <span className="block w-6 h-0.5 bg-gray-100 rounded"></span>
              </label>
              <div className="absolute top-20 left-0 w-full bg-gray-900 shadow-lg z-50 hidden peer-checked:block animate-fade-in">
                <ul className="flex flex-col gap-2 py-4 px-6 text-gray-100 font-medium">
                  {menuItems.map((item) => {
                    const isActive = typeof window !== 'undefined' && window.location.pathname === (item.href || (item.dropdown && item.dropdown[0]?.href));
                    return item.dropdown ? (
                      <li key={item.label} className="flex flex-col">
                        <span className="font-semibold px-4 py-2">{item.label}</span>
                        <ul className="pl-4">
                          {item.dropdown.map((sub) => {
                            const isSubActive = typeof window !== 'undefined' && window.location.pathname === sub.href;
                            return (
                              <li key={sub.href}>
                                <Link
                                  href={sub.href}
                                  className={`block px-4 py-2 rounded transition ${isSubActive ? 'text-blue-400' : ''}`}
                                >{sub.label}</Link>
                              </li>
                            );
                          })}
                        </ul>
                      </li>
                    ) : (
                      <li key={item.href}>
                        <Link
                          href={item.href}
                          className={`block px-4 py-2 rounded-full transition ${isActive ? 'text-blue-400' : ''}`}
                        >
                          {item.label}
                        </Link>
                      </li>
                    );
                  })}
                </ul>
              </div>
            </div>
          </nav>
        </header>
        {/* Main Content */}
        <main className="flex-1 w-full">
        {children}
        </main>
        {/* Footer */}
        <footer className="bg-gray-900 text-gray-100 mt-12 py-12 px-4">
          <div className="container mx-auto flex flex-col md:flex-row md:items-start md:justify-between gap-12 border-b border-gray-800 pb-8">
            <div className="flex flex-col items-center md:items-start md:w-1/4 gap-4">
              <Image src="/logo.png" alt="octobit8 logo" width={128} height={56} />
              <p className="text-sm text-gray-300 text-center md:text-left max-w-xs">Accelerating digital transformation with DevOps and Cloud solutions for modern businesses.</p>
              <div className="flex gap-3 mt-2">
                <a href="#" aria-label="LinkedIn" className="hover:text-blue-400 text-xl"><svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M19 0h-14c-2.76 0-5 2.24-5 5v14c0 2.76 2.24 5 5 5h14c2.76 0 5-2.24 5-5v-14c0-2.76-2.24-5-5-5zm-11 19h-3v-9h3v9zm-1.5-10.28c-.97 0-1.75-.79-1.75-1.75s.78-1.75 1.75-1.75 1.75.79 1.75 1.75-.78 1.75-1.75 1.75zm13.5 10.28h-3v-4.5c0-1.08-.02-2.47-1.5-2.47-1.5 0-1.73 1.17-1.73 2.39v4.58h-3v-9h2.88v1.23h.04c.4-.75 1.38-1.54 2.85-1.54 3.05 0 3.62 2.01 3.62 4.62v4.69z"/></svg></a>
                <a href="#" aria-label="Twitter" className="hover:text-blue-400 text-xl"><svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M24 4.56c-.89.39-1.84.65-2.84.77a4.93 4.93 0 002.16-2.72c-.95.56-2.01.97-3.13 1.19a4.92 4.92 0 00-8.39 4.48c-4.09-.2-7.72-2.17-10.15-5.15a4.93 4.93 0 001.52 6.57c-.8-.02-1.56-.25-2.22-.62v.06a4.93 4.93 0 003.95 4.83c-.39.11-.8.17-1.22.17-.3 0-.59-.03-.87-.08a4.93 4.93 0 004.6 3.42A9.87 9.87 0 010 21.54a13.94 13.94 0 007.56 2.22c9.05 0 14-7.5 14-14v-.64c.96-.7 1.8-1.56 2.46-2.54z"/></svg></a>
                <a href="#" aria-label="Facebook" className="hover:text-blue-400 text-xl"><svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M22.675 0h-21.35c-.733 0-1.325.592-1.325 1.326v21.348c0 .733.592 1.326 1.325 1.326h11.495v-9.294h-3.128v-3.622h3.128v-2.671c0-3.1 1.893-4.788 4.659-4.788 1.325 0 2.463.099 2.797.143v3.24l-1.918.001c-1.504 0-1.797.715-1.797 1.763v2.312h3.587l-.467 3.622h-3.12v9.294h6.116c.733 0 1.325-.593 1.325-1.326v-21.349c0-.733-.592-1.325-1.325-1.325z"/></svg></a>
              </div>
            </div>
            <div className="flex flex-col gap-2 min-w-[120px]">
              <h3 className="font-semibold mb-2 text-white">Company</h3>
              <ul className="space-y-1 text-sm">
                <li><Link href="/about" className="hover:underline">About</Link></li>
                <li><Link href="/careers" className="hover:underline">Careers</Link></li>

              </ul>
            </div>
            <div className="flex flex-col gap-2 min-w-[120px]">
              <h3 className="font-semibold mb-2 text-white">Services</h3>
              <ul className="space-y-1 text-sm">
                <li><Link href="/services/devops" className="hover:underline">DevOps & Cloud</Link></li>
              </ul>
            </div>
            <div className="flex flex-col gap-2 min-w-[180px]">
              <h3 className="font-semibold mb-2 text-white">Contact</h3>
              <ul className="space-y-1 text-sm">
                <li>Email: <a href="mailto:contact@octobit8.com" className="hover:underline">contact@octobit8.com</a></li>
                <li>Phone: <a href="tel:+919923706784" className="hover:underline">+91-9923706784</a></li>
                <li><span className="font-semibold">Registered Office:</span><br/>185 BARA LAL CHRAIST NAGAR, Varanasi, Uttar Pradesh, India, 221007</li>
                <li><span className="font-semibold">Noida Virtual Office:</span><br/>7th Floor, Plot A/8A, Knowledge Boulevard, Block A, Industrial Area, Sector 62, Noida, Uttar Pradesh</li>
              </ul>
            </div>
          </div>
          <div className="container mx-auto mt-8 flex flex-col md:flex-row items-center justify-between gap-4 pt-4 text-xs text-gray-400">
            <div>&copy; {new Date().getFullYear()} octobit8. All rights reserved.</div>
            <div className="flex gap-4">
              <a href="/privacy" className="hover:underline">Privacy Policy</a>
              <a href="/terms" className="hover:underline">Terms of Service</a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
